### ISSUE TITLE
Expired Discord invite link

### ISSUE THREAD

**Issue by IllusionMan1212** [BrowserJam/browserjam#1]
As the title says. Can't join the Discord because of the expired invite.

**Comment by ADKaster** [comment]
Here's an updated link until we can update the readme:
https://discord.gg/MAmkZ5BPEK

**Comment by ADKaster** [comment]
Closed with https://github.com/BrowserJam/browserjam/commit/b01e389642dc0f2e3da2f6dd7765cca74704792d
